export const ACTIONS = {
    JOIN: 'join',
    LEAVE: 'leave',
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    ADD: 'add',
    REMOVE: 'remove',
    SEND: 'send',
    RECEIVE: 'receive',
    CONNECT: 'connect',
    DISCONNECT: 'disconnect',
    CONNECTED: 'connected',
    DISCONNECTED: 'disconnected',
    CONNECTING: 'connecting',
    DISCONNECTING: 'disconnecting',
    CONNECTED_TO: 'connectedTo',
    DISCONNECTED_FROM: 'disconnectedFrom',
    ADD_PEER: 'addPeer',
    RELAY_ICE: 'relayIce',
    RELAY_SDP: 'relaySdp',
    ICE_CANDIDATE: 'iceCandidate',
    SESSION_DESCRIPTION: 'sessionDescription',
    REMOVE_PEER: 'removePeer',
};